// Generated by CoffeeScript 1.7.1

/*
Handle logins
 */

(function() {
  var widget;

  Ember.User = Ember.Object.extend({
    userId: null,
    token: null,
    name: null,
    nick: null,
    picture: null,
    identities: null,
    init: function() {
      this._super();
      return client.currentUser = {
        userId: this.get("userId"),
        mobileServiceAuthenticationToken: this.get("token")
      };
    },
    baseObj: function() {
      return {
        userId: this.get("userId"),
        token: this.get("token"),
        name: this.get("name"),
        nick: this.get("nick"),
        picture: this.get("picture"),
        identities: this.get("identities")
      };
    }
  });

  if (window.location.hash.match(/^#access_token/)) {
    widget = new Auth0Widget({
      domain: 'appti2ude.auth0.com',
      clientID: '4QBrlEZHS38TjIeyubMXCasvau2bJALW',
      callbackURL: 'http://appti2ude.com/',
      callbackOnLocationHash: true
    });
    widget.parseHash(window.location.hash, function(profile, id_token, access_token, state) {
      return widget.getClient().getDelegationToken("TiM6jLgzB6kRD28zrnoB9XsiIAP9vKme", id_token, {
        scope: "openid"
      }, function(err, delegationResult) {
        App.user = Ember.User.create({
          userId: profile.user_id,
          token: delegationResult.id_token,
          name: profile.name,
          nick: profile.nickname,
          picture: profile.picture,
          identities: profile.identities
        });
        App.LoginStateManager.send("login");
        $.cookie("currentUser", JSON.stringify(App.user.baseObj()), {
          domain: ".appti2ude.com"
        });
        window.location.href = "http://www.appti2ude.com/#/app/search";
        return console.log("Moving routes");
      });
    });
    window.location.hash = "#/";
    window.location.hash.substring(1);
  }


  /*
    End logins
   */


  /*
    Create the application
   */

  window.App = Ember.Application.create();


  /*
    Temp: todo: Create fixture adapter for testing
   */

  App.ApplicationAdapter = DS.FixtureAdapter.extend();


  /*
    Handles authenticated state
   */

  App.LoginStateManager = Ember.StateManager.create({
    initialState: (function() {
      if (($.cookie("currentUser") != null) && (App.user == null)) {
        App.user = Ember.User.create(JSON.parse($.cookie("currentUser")));
      }
      if (client.currentUser != null) {
        return "Authenticated";
      } else {
        return "NotAuthenticated";
      }
    })(),
    completed: false,
    Authenticated: Ember.State.create({
      enter: function() {
        return console.log("enter " + this.name);
      },
      logout: function(manager, context) {
        return manager.transitionTo("NotAuthenticated");
      }
    }),
    NotAuthenticated: Ember.State.create({
      enter: function() {
        return console.log("enter " + this.name);
      },
      login: function(manager, credentials) {
        console.log(credentials);
        return manager.transitionTo("Authenticated");
      }
    })
  });


  /*
    An authenticated controller
   */

  Ember.AuthenticatedController = Ember.Controller.extend({
    authStateBinding: Ember.Binding.oneWay("App.LoginStateManager.currentState.name"),
    authState: null,
    pictureBinding: "App.user.picture",
    picture: null,
    nickBinding: Ember.Binding.oneWay("App.user.nick"),
    nick: null,
    isAuthenticated: (function() {
      if (this.get("authState") === "Authenticated") {
        Ember.bind(this, "picture", "App.user.picture");
        Ember.bind(this, "nick", "App.user.nick");
        console.log(this.get("nick"));
        return true;
      } else {
        return false;
      }
    }).property("authState")
  });


  /*
    An authenticated route
   */

  Ember.AuthenticatedRoute = Ember.Route.extend({
    authStateBinding: Ember.Binding.oneWay("App.LoginStateManager.currentState.name"),
    authState: null,
    isAuthenticated: (function() {
      return this.get("authState") === "Authenticated";
    }).property("authState"),
    authenticationChanged: (function() {
      if (!this.get("isAuthenticated")) {
        this.transitionTo("index");
        return console.log("Tried accessing authenticated page, redirected to index.");
      }
    }).observes("authState"),
    beforeModel: function() {
      return this.authenticationChanged();
    }
  });


  /*
    The application controller
   */

  App.ApplicationController = Ember.AuthenticatedController.extend({
    actions: {
      login: function(provider) {
        widget = new Auth0Widget({
          domain: 'appti2ude.auth0.com',
          clientID: '4QBrlEZHS38TjIeyubMXCasvau2bJALW',
          callbackURL: 'http://appti2ude.com/',
          callbackOnLocationHash: true
        });
        return widget.signin();
      },
      logout: function() {
        $.removeCookie("currentUser", {
          domain: ".appti2ude.com"
        });
        return App.LoginStateManager.send("logout");
      }
    }
  });

}).call(this);

//# sourceMappingURL=app.map
