// Generated by CoffeeScript 1.7.1
(function() {
  App.IndexRoute = Ember.Route.extend({
    model: function() {
      return this.store.find('app');
    }
  });

}).call(this);

//# sourceMappingURL=index.map
