// Generated by CoffeeScript 1.7.1
(function() {
  App.IndexRoute = Ember.Route.extend({
    authStateBinding: Ember.Binding.oneWay("App.LoginStateManager.currentState.name"),
    authState: null,
    isAuthenticated: (function() {
      return this.get("authState") === "Authenticated";
    }).property("authState"),
    model: function() {
      return this.store.find('app');
    }
  });

}).call(this);

//# sourceMappingURL=index.map
