// Generated by CoffeeScript 1.7.1
(function() {
  App.IndexRoute = Ember.Route.extend({
    authStateBinding: Ember.Binding.oneWay("App.LoginStateManager.currentState.name"),
    authState: null,
    isAuthenticated: (function() {
      return this.get("authState") === "Authenticated";
    }).property("authState"),
    model: function() {
      return this.store.find('app');
    }
  });

  App.AppRoute = Ember.Route.extend({
    actions: {
      willTransition: function(transition) {
        if ($("a.brand.dropdown-toggle").is(":visible") === true) {
          $("button.navbar-toggle").click();
        }
        return true;
      }
    }
  });

}).call(this);

//# sourceMappingURL=index.map
