// Generated by CoffeeScript 1.7.1
(function() {
  App.Router.map(function() {
    return this.resource('app', function() {
      return this.route("new");
    });
  });

  App.AppNewRoute = Ember.AuthenticatedRoute.extend();

}).call(this);

//# sourceMappingURL=Router.map
