// Generated by CoffeeScript 1.7.1
(function() {
  App.Router.map(function() {
    return this.resource('newapp', {
      path: 'app/new'
    });
  });

}).call(this);

//# sourceMappingURL=Router.map
