// Generated by CoffeeScript 1.7.1
(function() {
  App.Router.map(function() {
    return this.resource('app', function() {
      this.resource("search", function() {
        return this.route("results", {
          path: ":search_term"
        });
      });
      this.route("new", {
        path: "new/:id"
      });
      this.route("show", {
        path: ":id"
      });
      return this.route("edit", {
        path: ":id/edit"
      });
    });
  });

}).call(this);

//# sourceMappingURL=Router.map
