// Generated by CoffeeScript 1.7.1
(function() {
  Ember.Handlebars.registerBoundHelper('money', function(value) {
    return accounting.formatMoney(value / 100);
  });

  Handlebars.registerHelper("login", function() {
    var widget;
    widget = new Auth0Widget({
      domain: 'appti2ude.auth0.com',
      clientID: '4QBrlEZHS38TjIeyubMXCasvau2bJALW',
      callbackURL: 'https://appti2ude.auth0.com/mobile',
      callbackOnLocationHash: true,
      scope: "openid"
    });
    widget.parseHash(window.location.hash, function(profile, id_token, access_token, state) {

      /*
        *store the profile and id_token in a cookie or local storage
       $.cookie('profile', profile)
       $.cookie('id_token', id_token)
       */
      console.log(profile);
      return console.log(id_token);
    });
    widget.signin({
      container: 'root',
      chrome: true
    });
    return "";
  });

}).call(this);

//# sourceMappingURL=helpers.map
